apiVersion: v1
kind: Service
metadata:
  name: {{ template "nextcloud.fullname" . }}
  labels:
    app: {{ template "nextcloud.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  {{- if eq .Values.serviceType "LoadBalancer" }}
  loadBalancerIP: {{ default "" .Values.nextcloud.loadBalancerIP }}
  {{- end }}
  ports:
  - name: http
    port: {{ default "80" .Values.nextcloud.port }}
    targetPort: 80
  selector:
    app: {{ template "nextcloud.fullname" . }}
